name: graphRL
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit=11.1
  - jupyterlab=1.2
  - pip=20.0
  - python=3.7
  - pytorch
  - tensorboard=2.1
  - torchvision
  - torchtext