name: graphRL
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - tensorboard=2.1.1
  - python=3.7
  - pip
  - jupyterlab
  - pytorch=1.8.1
  - cudatoolkit=11.1
  - networkx
  - scipy
  - torchtext=0.9.1
  - torchvision=0.9.1
  - tensorboardx
  - easydict
  - pyyaml
  - pip:
      - cycler==0.10.0
      - kiwisolver==1.3.1
      - matplotlib==2.2.3
      - pytz==2021.1
      - tensorboard_logger
      - pyemd
