name: graphRL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py37h5e8e339_0
  - argon2-cffi=20.1.0=py37h5e8e339_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.4.13=h06a4308_1
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.5=py37hc58025e_0
  - chardet=4.0.0=py37h89c1867_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py37h5d9358c_0
  - cudatoolkit=11.1.1=h6406543_8
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.0.7=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.3.0=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h0708190_1
  - glib=2.68.1=h36276a3_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=1.30.0=pyh44b312d_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.37.1=py37hb27c1af_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.0.1=py37h89c1867_0
  - ipykernel=5.5.4=py37h085eea5_0
  - ipython=7.23.1=py37h085eea5_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py37h89c1867_2
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py37h89c1867_0
  - jupyterlab=1.2.16=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.3.1=py37h2531618_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.16.0=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.41.0=h7f98852_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvm-openmp=11.1.0=h4bd325d_1
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=1.1.1=py37h5e8e339_3
  - matplotlib=3.3.4=py37h06a4308_0
  - matplotlib-base=3.3.4=py37h62a2d02_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py37h5e8e339_1003
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py37h8f50634_2
  - mkl_fft=1.3.0=py37h902c9e0_1
  - mkl_random=1.2.0=py37h9fdb41a_1
  - multidict=5.1.0=py37h5e8e339_1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h89c1867_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=2.2=py37_1
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.3.0=pyha770c72_1
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.9=pyh44b312d_0
  - pandoc=2.12=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py37he98fc37_0
  - pip=20.0.2=py_2
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - protobuf=3.16.0=py37hcd2ae1e_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h5e8e339_2
  - pysocks=1.7.1=py37h89c1867_3
  - python=3.7.10=hffdb5ce_100_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.8.1=py3.7_cuda11.1_cudnn8.0.5_0
  - pyzmq=22.0.3=py37h336d617_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scipy=1.6.2=py37h91f5cce_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37h89c1867_3
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.35.5=h74cdb3f_0
  - tensorboard=2.1.1=py_1
  - terminado=0.9.4=py37h89c1867_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=h21135ba_1
  - torchtext=0.9.1=py37
  - torchvision=0.9.1=py37_cu111
  - tornado=6.1=py37h5e8e339_1
  - tqdm=4.60.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - yarl=1.6.3=py37h5e8e339_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=haebb681_0
prefix: /home/ousmanetouat/anaconda3/envs/graphRL
