name: graphRL
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - tensorboard=2.1.1
  - python=3.7
  - pip
  - jupyter
  - jupyterlab
  - pytorch=1.8.1
  - cudatoolkit=11.1
  - networkx=2.3
  - scipy
  - tensorboardx
  - easydict
  - pyyaml
  - pandas
  - pip:
      - cycler==0.10.0
      - kiwisolver==1.3.1
      - matplotlib==2.2.3
      - pytz==2021.1
      - tensorboard_logger
      - pyemd
      - gym
      - sklearn
      - tqdm
      - numpy
