name: graphRL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=3.0.4
  - click=8.0.0
  - coverage=5.5
  - cryptography=3.4.7
  - cudatoolkit=11.1.1
  - cython=0.29.23
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ffmpeg=4.2.2
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.30.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.36.1
  - idna=2.10
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=3.0.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libidn2=2.3.1
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.0
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - multidict=5.1.0
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.7.2
  - ninja=1.10.2
  - notebook=6.3.0
  - numexpr=2.7.3
  - numpy=1.20.2
  - numpy-base=1.20.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.3.1
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.0.1
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - protobuf=3.14.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.8.1
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - pytorch=1.8.1
  - pytz=2021.1
  - pyzmq=20.0.0
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.4
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorboardx=2.2
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - torchtext=0.9.1
  - torchvision=0.9.1
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - cycler==0.10.0
    - easydict==1.9
    - kiwisolver==1.3.1
    - matplotlib==2.2.3
    - networkx==2.3
    - pyemd==0.5.1
    - pyyaml==5.4.1
